### ISSUE TITLE
Homepage: W3C 35 errors

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Academic-Group#1]
![image](https://cloud.githubusercontent.com/assets/17717843/15561898/1070598e-232d-11e6-8bad-5422e1432ef8.png)

https://validator.w3.org/nu/?doc=http%3A%2F%2Fwww.academicgroup-imp.stage.titanweb.com.au%2F

**Comment by jsemblantetitanweb** [comment]
Plugin Issue
