### ISSUE TITLE
Search Result: post title should be the same color to the site theme

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Academic-Group#121]
![image](https://cloud.githubusercontent.com/assets/17717843/15885457/e352f940-2d89-11e6-8d5b-dcaa2daf3723.png)

**Comment by jsemblantetitanweb** [comment]
I have look the design and it seems the color red is just following the color given in the design. Should we still enhance it with color blue ? Screenshot below with (Why choose us page):

![image](https://cloud.githubusercontent.com/assets/18159491/15995423/b96e08a0-314d-11e6-8533-c3a23c2167e0.png)
