### ISSUE TITLE
Product Listing: retain the sidebar menu in all  product pages

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Academic-Group#131]
![image](https://cloud.githubusercontent.com/assets/17717843/16035861/e46d6a06-324b-11e6-9050-6a660c4ef045.png)

**Comment by jsemblantetitanweb** [comment]
Since the sidebar depends on the list of sub categories that the category contains, this is not a bug. Categories without sub categories are normally displaying such "NO CATEGORIES" in the sidebar for it can't display anything.

**Comment by roseliesromeo** [comment]
Sidebar should display in category/subcategory and single page as per design.

**Comment by roseliesromeo** [comment]
Not fixed in single pages. See bug #159
