### ISSUE TITLE
General: removed all images with watermark

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Academic-Group#133]
![image](https://cloud.githubusercontent.com/assets/17717843/16037757/8e6fa692-3254-11e6-8fe1-eac56daeced6.png)

**Comment by jsemblantetitanweb** [comment]
The watermark is part of the image. User could just remove this by placing a new image without watermark.

**Comment by roseliesromeo** [comment]
Developers shouldn't be adding images with water marks in the first place.
