### ISSUE TITLE
Payment Gateway - Resolution Error: Qty and Cost is hidden in lower resolution

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Academic-Group#136]
Resolution: below 480 viewport

![image](https://cloud.githubusercontent.com/assets/17717843/16065239/9087d300-32db-11e6-80a1-4765d91a2916.png)

**Comment by jsemblantetitanweb** [comment]
Note: This is being done in a different responsive way. It is horizontally scrollable in mobile viewports starting 768px
