### ISSUE TITLE
Cart - Resolution Error: Quantity and Total fields are hidden in lower resolution

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Academic-Group#138]
Resolution: 470 and below

![image](https://cloud.githubusercontent.com/assets/17717843/16065408/0b2c3f82-32dd-11e6-81be-61f96618d57d.png)

**Comment by jsemblantetitanweb** [comment]
Note: This is being done in a different responsive way. It is horizontally scrollable in mobile viewports starting 768px
