### ISSUE TITLE
Cart - RETURN TO SHOP button: incorrect link 

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Academic-Group#142]
![image](https://cloud.githubusercontent.com/assets/17717843/16066771/b6b51850-32e8-11e6-91df-f4aaa4ef43cb.png)

**Comment by roseliesromeo** [comment]
![image](https://cloud.githubusercontent.com/assets/11186313/16439660/34e0f334-3ded-11e6-9be3-b80c600851ab.png)
