### ISSUE TITLE
Order Received - Billing Address: some informations are missing

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Academic-Group#146]
![image](https://cloud.githubusercontent.com/assets/17717843/16066988/bae2a184-32ea-11e6-9565-cf029d5444ff.png)

**Comment by jsemblantetitanweb** [comment]
Note: Pending for now. I've send an email to the project manager for this to be clarified. Right now the checkout page that you are seeing on the stage is the default woocommerce checkout page. The previous checkout page is being reset.

**Comment by roseliesromeo** [comment]
Waiting for confirmation

**Comment by jsemblantetitanweb** [comment]
This is now done by Christian.
