### ISSUE TITLE
Product Listing: no categories

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Academic-Group#147]
![image](https://cloud.githubusercontent.com/assets/17717843/16067384/7f3ed856-32ee-11e6-8736-127bc1f9d4bc.png)

**Comment by jsemblantetitanweb** [comment]
This is displaying because there are no sub categories found for the specific category.

**Comment by roseliesromeo** [comment]
Same sidebar should display on the category, subcategory and single page as implied by the design.
