### ISSUE TITLE
Forgot password: Inconsistent font color of the validation message.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Academic-Group#156]
![image](https://cloud.githubusercontent.com/assets/11186313/16509268/8a5aa914-3f6d-11e6-857c-bf581ef2ddc8.png)

**Comment by jsemblantetitanweb** [comment]
![image](https://cloud.githubusercontent.com/assets/18159491/16549757/2a0f5248-41d5-11e6-966c-89c98cf82a1f.png)

How can I replicate the issue ? It is already being trap to the default html email validator. See attach screenshot
