### ISSUE TITLE
Product single: Image gallery thumbnails should spread within the width of the featured image specified in the design.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Academic-Group#172]
![image](https://cloud.githubusercontent.com/assets/11186313/16514211/19680df2-3f9d-11e6-8651-fbd2049319ce.png)

**Comment by jsemblantetitanweb** [comment]
It is already spreading within the width of the featured image. See screenshot

![image](https://cloud.githubusercontent.com/assets/18159491/16548914/fffabaf6-41ca-11e6-8557-2195ef767bb5.png)
