### ISSUE TITLE
Homepage - Video Section: please clear the image if the play button is hidden

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Academic-Group#25]
![image](https://cloud.githubusercontent.com/assets/17717843/15568613/6862a9a8-235f-11e6-85f1-ce1c7adb3d28.png)

**Comment by dremensayson** [comment]
Please do not removed the image.

**Comment by roseliesromeo** [comment]
Remove blur overlay when button is removed.

**Comment by jsemblantetitanweb** [comment]
We cant remove the blur overlay through css. The blur that is being overlay on the image is part og the image.
