### ISSUE TITLE
Homepage: please position the banner content below the featured image in mobile resolution begin with 768 viewport

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Academic-Group#28]
![image](https://cloud.githubusercontent.com/assets/17717843/15570161/46b1dc36-2367-11e6-9a14-9583308bfb5d.png)

**Comment by jsemblantetitanweb** [comment]
This is already fix but I put it in viewport 990px below for the reason that the banner is already being mobile responsive and staying the leadins till 768px will make the leadin section overlap into the banners height.
