### ISSUE TITLE
Homepage - Resolution Checking: misaligned newsletter in 1199 and below resolution

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Academic-Group#29]
![image](https://cloud.githubusercontent.com/assets/17717843/15594520/d0dd90ae-23e8-11e6-9390-58d8358624d1.png)

**Comment by jsemblantetitanweb** [comment]
![image](https://cloud.githubusercontent.com/assets/18159491/16068564/693cab68-32f9-11e6-91a2-fb990e2d0271.png)

This is already been fix. Screenshot attached
