### ISSUE TITLE
Homepage - Resolution Checking: banner is not responsive

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Academic-Group#33]
![image](https://cloud.githubusercontent.com/assets/17717843/15595123/fbeab5c8-23ee-11e6-872b-564c1049095b.png)

**Comment by jsemblantetitanweb** [comment]
Note: On resolution 768 below banner wont be re-sizing to  a more smaller size. I have limit the height for the content purpose.

**Comment by dremensayson** [comment]
You can position the banner content below the banner image. Please refer to this site. http://cpsnational.stage.titanweb.com.au/

**Comment by roseliesromeo** [comment]
Banner not fully responsive
