### ISSUE TITLE
cef Notifycation

### ISSUE THREAD

**Issue by L60008028** [titan-cebu/Academic-Group#40]
Desktop notification JS in the Google browser can be executed, But the CEF can not be implemented, why?

JS:
 var notification = new Notification('google notification!'); 
	notification.onshow = function () {
	 setTimeout(function () {
	    notification.close();
	 }, 3000);
	};

**Comment by jsemblantetitanweb** [comment]
Hello, where can I find the code ? As far as a I know desktop notification should have permission from user in order to work. The code above is not having any request permission. Thanks
