### ISSUE TITLE
Contact Us Now - Notification: missing post url

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Academic-Group#51]
![image](https://cloud.githubusercontent.com/assets/17717843/15598895/459b5d9a-2411-11e6-87d1-8282ff740723.png)

**Comment by jsemblantetitanweb** [comment]
The link is being shown when I test in my end. Screenshot below:

![image](https://cloud.githubusercontent.com/assets/18159491/15998316/ee469dae-316f-11e6-8c1d-1b0db10396b2.png)
