### ISSUE TITLE
Pre footer - Social media icon: misaligned and no space between other icon in 320 view port

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Academic-Group#54]
![image](https://cloud.githubusercontent.com/assets/17717843/15599380/7710adfe-2415-11e6-967b-3b811cd39ffc.png)

**Comment by jsemblantetitanweb** [comment]
![image](https://cloud.githubusercontent.com/assets/18159491/15924814/b27fb398-2e66-11e6-8378-ef978bb7325b.png)

I have check it in 320 viewport and it seems it is appearing correctly.
