### ISSUE TITLE
Parents: would like to ask how the parents sidebar menu (woocommerce menu) being implemented.

### ISSUE THREAD

**Issue by dremensayson** [titan-cebu/Academic-Group#87]
![image](https://cloud.githubusercontent.com/assets/17717843/15642171/2e77cd06-2678-11e6-802f-e1889a42584a.png)

Admin: try to edit the parent category but no effect in the site
![image](https://cloud.githubusercontent.com/assets/17717843/15642288/e3385a4e-2678-11e6-9287-d401a1ad5307.png)

**Comment by jsemblantetitanweb** [comment]
The woocommerce sidebar is being build up dynamically depending on the sub category of the current page category. For example. On "Parents", "Year 11 and 12" and "Year 9 and 10" is under the "Parents" category. This menu is not base on backend woocommerce menu.

**Comment by roseliesromeo** [comment]
What's the use of the WooCommerce menu? I don't there has to be woocommercemenu so it has to be removed.

**Comment by jsemblantetitanweb** [comment]
I have remove the woocommerce menu in the backend because our sidebar is being get dynamically base on the subcategories of the main category
